apiVersion: v1
kind: Pod
metadata:
  name: my-app
  annotations:
    gateman.kdex.dev/database: |
      {
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "name": "database",
        "expression": "resource.status.updatedReplicas >= 1"
      }
    gateman.kdex.dev/redis: |
      {
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "name": "redis",
        "expression": "resource.status.updatedReplicas >= 1"
      }
spec:
  schedulingGates:
  - name: gateman.kdex.dev/database
  - name: gateman.kdex.dev/redis
  containers:
  - name: nginx
    image: nginx

# kubectl patch pod nginx -p '[{"op": "remove", "path": "/spec/schedulingGates/*", "value": "gateman.kdex.dev/one"}]'