name: Tests

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.23.0'

      - name: Running Tests
        run: |
          go mod tidy
          make test
